# permissions for end users to edit presentationcontrols.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: presentationcontrol-editor-role
rules:
- apiGroups:
  - architecture.curriculum.my.domain
  resources:
  - presentationcontrols
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - architecture.curriculum.my.domain
  resources:
  - presentationcontrols/status
  verbs:
  - get
