# permissions for end users to view presentationcontrols.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: presentationcontrol-viewer-role
rules:
- apiGroups:
  - architecture.curriculum.my.domain
  resources:
  - presentationcontrols
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - architecture.curriculum.my.domain
  resources:
  - presentationcontrols/status
  verbs:
  - get
