apiVersion: architecture.curriculum.my.domain/v1alpha1
kind: PresentationControl
metadata:
  name: custom-secret-var
spec:
  formula: "s + ' is my Home!!'"
  parameters:
    s:
      value: "default/sample-secret-url"
      type: secret
